services:
  php-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-php-srv
    restart: unless-stopped
    volumes:
      - ./spa-api/:/var/www/html/spa-api/
    networks:
      - api-network
  nginx:
    image: nginx:alpine
    container_name: "api-nginx-srv"
    volumes:
      - ./spa-api/:/var/www/html/spa-api/
      - ./docker-config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-config/ssl:/etc/nginx/ssl
    ports:
      - 8080:80
      - 443:443
    restart: always
    networks:
      - api-network
  api-mysql:
    image: mysql:8.0.29-debian
    command: --default-authentication-plugin=mysql_native_password
    container_name: api-mysql-srv
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Senha@123456
      MYSQL_DATABASE: fabiano_front
    restart: always
    networks:
      - api-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: api-mysql-srv
      PMA_USER: root
      PMA_PASSWORD: Senha@123456
    restart: always
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
